# -*- coding: utf-8 -*-
"""Subplotting_Data_Distributions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLnFuIGoxFmG3t7BLsRU_UKKiEijBFrY

**Maestría en Inteligencia Artificial y Analítica de Datos**

Curso: *Programación para Analítica Descriptiva y Predictiva*

* Semestre: Enero-Junio 2026
* Profesor: Dr. Vicente García Jiménez
* Alumno: Ricardo Solano Monje
* Matrícula: 266221
* Unidad 1
* Práctica 9: Distribución de Datos con subplots en matplotlib
* Objetivo de la práctica: Hacer uso de subplots para visualizar diferentes distribuciones generadas con NumPy, almacenadas en DataFrames y graficadas en una misma figura.
* Realizado por: Ricardo Solano Monje

# Práctica 9 Distribución de Datos con plt.subplots()
**Objetivo**:
Utilizar plt.subplots() para visualizar diferentes distribuciones generadas con NumPy y almacenadas en un DataFrame.

Instrucciones:
* Genera un DataFrame con Pandas que contenga 1000 valores en cuatro columnas (Normal, Uniforme, Exponencial, Poisson).
* Crea una figura con plt.subplots(2, 2) para organizar los histogramas en una cuadrícula de 2x2.
* Grafica cada distribución en un subplot usando ax[i, j].hist().
* Agrega títulos a cada subplot y ajusta la disposición con tight_layout().
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def main(file_path=None):
    """ First of all, generate the data,
        Genera un DataFrame con Pandas que contenga 1000 valores en cuatro columnas (
    Normal, Uniforme, Exponencial, Poisson).
    """
    np.random.seed(42) # seed for reproducibility
    df = pd.DataFrame({
        'Normal': np.random.normal(0, 1, 1000),
        'Uniform': np.random.uniform(0, 1, 1000),
        'Exponential': np.random.exponential(1, 1000),
        'Poisson': np.random.poisson(3, 1000)
    })

    # Create subplots, Crea una figura con subplots plt.subplots(2, 2) para organizar los histogramas en una cuadrícula de 2x2.
    fig, axes = plt.subplots(2, 2, figsize=(10, 8)) #axes has a 2D shape (2, 2)
    # Plot each distribution, Grafica cada distribución en un subplot usando ax[i, j].hist().
    axes[0, 0].hist(df['Normal'], bins=30, edgecolor='black') #ax[i, j].hist() row =0 , col=0
    axes[0, 0].set_title('Normal Distribution') # Agrega títulos a cada subplot y...

    axes[0, 1].hist(df['Uniform'], bins=30, edgecolor='black') #ax[i, j].hist(), row=0= 1
    axes[0, 1].set_title('Uniform Distribution') # Agrega títulos a cada subplot y...

    axes[1, 0].hist(df['Exponential'], bins=30, edgecolor='black') #ax[i, j].hist() , row=1, col=0
    axes[1, 0].set_title('Exponential Distribution') # Agrega títulos a cada subplot y...

    axes[1, 1].hist(df['Poisson'], bins=30, edgecolor='black') #ax[i, j].hist(), row=1, col=1
    axes[1, 1].set_title('Poisson Distribution') # Agrega títulos a cada subplot y...

    plt.tight_layout() # ...y ajusta la disposición con tight_layout().

    # Save figure to image if file path provided
    if file_path:
        plt.savefig(file_path, dpi=300, bbox_inches='tight')
    plt.show()

    return df

if __name__ == "__main__":
     # Run with optional save path
    # file_path="./"
    df = main(file_path='wired_indexing_distributions_histogram.png')

    # Display first few rows
    print("Shape of the Generated DataFrame:", df.shape)
    print("\nFirst 5 rows:")
    print(df.head())
    print("\nSummary statistics for each distribution:")
    print(df.describe())

"""### Same result as before,
*But implemented using 2 functions. It iterates over axes  and dataframe at the same time using zip.*
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Create a Pandas DataFrame containing 1000 values in four columns (Normal, Uniform, Exponential, Poisson).

def generate_distributions(n=1000, seed=42):# seed to be able to replicate
    """Generate four different distributions with n values each."""
    np.random.seed(seed)  # for reproducibility

    df = pd.DataFrame({
        'Normal': np.random.normal(0, 1, n),
        'Uniform': np.random.uniform(0, 1, n),
        'Exponential': np.random.exponential(1, n),
        'Poisson': np.random.poisson(3, n)
    })
    return df #returns generated dataframe

def plot_distributions(df, figsize=(10, 8)):
    """Create 2x2 subplot grid with histograms of each distribution.
    Crea una figura con plt.subplots(2, 2) para organizar los histogramas en una cuadrícula de 2x2.
    """
    fig, axes = plt.subplots(2, 2, figsize=figsize) # Create a 2x2 grid of subplots. #axes is a 2D numpy array shape (2, 2)

    # # Flatten axes, the 2D array of axes into a 1D array for easier iteration,
    axes_flat = axes.flatten()  #axes is a 1D numpy array shape (4,)a 1-dimensional (1D) array containing 4 elements.
    #print(f" axes flatten = {axes_flat.shape}")
    # Plot each column in a subplot, Grafica cada distribución en un subplot usando ax[i, j].hist().
    # Iterate over the flattened axes and plot data
    for ax, col in zip(axes_flat, df.columns): # zip help us to use the same index for df.columns as well as for axes_flat
        #print(f" col = {col}, df.columns= {df.columns}, ax = {ax}")
        ax.hist(df[col], bins=30, edgecolor='black', alpha=0.7) # valores núméricos de cada columna en df[col]
        ax.set_title(f'{col} Distribution') # Agrega títulos a cada subplot ,Título de la columna en col
        ax.set_xlabel('Value')
        ax.set_ylabel('Frequency')

    plt.tight_layout() # Agrega títulos a cada subplot y ajusta la disposición con tight_layout().
    plt.show()
    return fig, axes

  #Main function
def main(file_path=None):

    # Generate data, Genera un DataFrame con Pandas que contenga 1000 valores en cuatro columnas (Normal, Uniforme, Exponencial, Poisson).
    df = generate_distributions() # gets the dataframe
 #   print(f" Generated dataframe {df}")
    # Create the visualization, Grafica cada distribución en un subplot usando ax[i, j].hist().
    fig, axes = plot_distributions(df) #plots the info of the dataframe

    # Save figure to image if file path provided
    if file_path:
        plt.savefig(file_path, dpi=300, bbox_inches='tight')

   # plt.show()
    return df

if __name__ == "__main__":
    # Run with optional save path
    # file_path="./"
    df = main(file_path='distributions_histogram.png')

    # Display first few rows
    print("Shape of the Generated DataFrame:", df.shape)
    print("\nFirst 5 rows:")
    print(df.head())
    print("\nSummary statistics for each distribution:")
    print(df.describe())

